name: Step1

on:
  workflow_call:
    inputs:
      image_name:
        description: "test"
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.image_name }}"
